### ISSUE TITLE
orb-go/internal/apierror.go: Can not use Error Constants because they are not exported 

### ISSUE THREAD

**Issue by as2643** [orbcorp/orb-go#133]
Hi! 

I am working with the orb api and wanted to use the Error Constants that are defined in `apierror.go`. However, this is an internal file, so we can not use anything from this file and these error codes are not re-exported anywhere as well. It would be great if there was a way to export the error codes so we could use them! 

Thanks!

**Comment by rattrayalex** [comment]
Thanks for the feedback, we're looking into this.

**Comment by dackerman** [comment]
Thank you @enozcan and @as2643 - agreed, there's no reason for us not to expose these error types.  We went ahead and and exposed them in version 0.32.0, which you can find here: https://github.com/orbcorp/orb-go/releases/tag/v0.32.0
